import Layout from '@/components/Layout';
import Head from 'next/head';
import Image from 'next/image';
import profilePic from '../../public/images/profile/developer-pic-1.png';
import AnimatedText from '@/components/AnimatedText';
import Link from 'next/link';
import { LinkArrow } from '@/components/Icons';
import HireMe from '@/components/HireMe';
import lightBlub from '../../public/images/svgs/miscellaneous_icons_1.svg';
import { Container } from 'postcss';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main
        className="flex items-center text-dark w-full min-h-scree 
      dark:text-light "
      >
        <Layout className="pt-0">
          <div className="flex items-center justify-between w-full">
            <div className="w-1/2">
              <Image
                src={profilePic}
                alt="Obadea"
                className="w-full h-auto"
                priority
                sizes="(max-width:768px) 100vw,
                (max-width: 1200px) 50vw,
                50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center">
              <AnimatedText
                text="Turning Vision Into Reality With Code And Design."
                className="!text-6xl !text-left cursor-default"
              />
              <p className="my-4 text-base font-medium cursor-default">
                As a proficient front-end developer, I specialize in creating
                sleek and user-friendly interfaces. Check out my latest React.js
                projects and articles to see my expertise in action. I'm
                passionate about bringing ideas to life through innovative web
                development.
              </p>
              <div className="flex items-center self-start mt-2">
                <Link
                  href="/GbengaObadiahResume.pdf"
                  target="_blank"
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark
                  
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light
                  "
                  download={true}
                >
                  Resume <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link
                  href="mailto:obadeagbenga@gmail.com"
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light
                  "
                >
                  Contact
                </Link>
              </div>
            </div>
          </div>
        </Layout>

        <HireMe />
        <div className="absolute right-8 bottom-8 inline-block w-20">
          <Image
            src={lightBlub}
            alt="Obadiah Gbenga"
            className="w-full h-auto"
          />
        </div>
      </main>
    </>
  );
}
